config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'about', to: 'home#about'
  get 'terms', to: 'home#terms'
  resources :photos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, :description, :image, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def terms
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      flash[:success] = 'Utworzono nowe zdjęcie.'
      redirect_to @photo
    else
      flash.now[:danger] = 'Nie można utworzyć zdjęcia.'
      render :new
    end
  end

  def edit
  end

  def update

    if @photo.update(photo_params)
      flash[:success] = 'Aktualizacja przebiegła pomyślnie.'
      redirect_to @photo
    else
      flash.now[:danger] = 'Nie udało się zaktualizować.'
      render :edit
    end
  end

  def destroy
    @photo.destroy
    flash[:success] = 'Zdjęcie zostało usunięte.'
    redirect_to photos_url
  end

private
  def set_photo
    @photo = Photo.find(params[:id])
  end
  
  def photo_params
    params.require(:photo).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% content_for :title, "O stronie" %>
<h1>Kilka słów o stronie</h1>
<p>Projekt X</p>

app/views/home/index.html.erb
<% content_for :title, "Strona główna" %>
<h1>Picturest</h1>

app/views/home/terms.html.erb
<% content_for :title, "Warunki korzystania z serwisu" %>
<h1>Zasady korzystania z serwisu</h1>

<p>Kiedyś będzie tu ogrom warunków, których i tak nikt nie spełni:)</p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <%= link_to 'Zasady korzystania z serwisu', terms_path, class: 'pull-right' %>
    <p class="text-muted">Strona stworzona do nauki RAILS</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Picturest", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Strona główna", root_path %></li>
        <li><%= link_to "Zdjęcia", photos_path %></li>
        <li><%= link_to "O nas", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logowanie", '#' %></li>
        <li><%= link_to "Rejestracja", '#' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picturest | <%= content_for :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'ruby.png' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/photos/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(photo) do |f| %>
      <div class="form-group">
        <%= f.label :title, 'Tytuł' %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Wpisz tytuł' %>
      </div>
      <div class="form-group">
        <%= f.label :description, 'Opis' %>
        <%= f.text_field :description, class: 'form-control', placeholder: 'Wpisz opis' %>
      </div>

      <div class="form-group">
        <%= f.label :image, 'Plik zdjęcia' %>
        <%= f.file_field :image %>
      </div>

      <div class="actions"></div>
        <%= f.submit 'Zapisz zdjęcie', class: 'btn btn-primary'%>
      </div>

    <% end %>
  </div>
</div>

app/views/photos/edit.html.erb
<% content_for :title, "Edycja zdjęcia" %>

<h1>Edycja zdjęcia</h1>

<%= render 'form', photo: @photo %>

app/views/photos/index.html.erb
<% content_for :title, 'Zdjęcia' %>

<h1>
  Zdjęcia
  <%= link_to "Dodaj zdjęcie", new_photo_path, class: 'btn btn-primary pull-ringht' %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tytuł</th>
      <th>Opis</th>
      <th>Plik</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.title, photo_path(photo) %></td>
        <td><%= photo.description %></td>
        <td><%= image_tag photo.image_url, height: 70 %></td>
        <td><%= link_to "Edytuj", edit_photo_path(photo) %></td>
        <td><%=
              link_to 'Usuń', photo_path(photo), method: :delete,
                data: { confirm: 'Na pewno chcesz usunąć zdjęcie?' }
            %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/photos/new.html.erb
<% content_for :title, 'Nowe zdjęcie' %>

<h1>Nowe zdjęcie</h1>

<%= render 'form', photo: @photo %>

app/views/photos/show.html.erb
<% content_for :title, @photo.title %>

<h1>
  <%= @photo.title %>
</h1>

<p>
  <strong>Opis:</strong>
  <%= @photo.description %>
</p>

<p>
  <%= image_tag @photo.image_url, height: 400 %>
</p>